### ISSUE TITLE
Mod causes crashes with chat messages generated by mods.

### ISSUE THREAD

**Issue by The-Scout** [daPoseidonGuy/Teams#3]
[The pastebin of the error](https://pastebin.com/75pLTXtT)

Steps for replication, Install this mod with not enough wands or another easily tested mod.
Use wand until runs out of charge and or chage mode.

Get the crash/error

**Comment by godemperoroftheworld** [comment]
Ok, so all my chat handling is encapsulated by a check to make sure the "type" of chat received is of ChatType.CHAT and not GAME_INFO or SYSTEM. 

I guess the mods that give you the issue aren't using the appropriate chat type. I will add an additional check within my mod to compensate :) 

I'll post here when I'm done so you can verify that it's fixed :)

**Comment by godemperoroftheworld** [comment]
https://drive.google.com/file/d/1FAhhfJ0oh5sNckzYqGkYEZLSjyYpPMnP/view?usp=sharing

Does this solve the issue @The-Scout?

**Comment by The-Scout** [comment]
Verifying now

**Comment by The-Scout** [comment]
Yep seems to be fixed thank you very much

**Comment by godemperoroftheworld** [comment]
Great! I'll post the update on curseforge tonight or tomorrow :)
