### ISSUE TITLE
1.16.x support?

### ISSUE THREAD

**Issue by InferusAnima** [daPoseidonGuy/Teams#5]
Are you going to make 1.16.x version?

**Comment by godemperoroftheworld** [comment]
Rewrite is in progress

**Comment by XxInvictus** [comment]
I have done a good chunk of the conversion in my Fork, I have it loading with 1.16.5 and SOME functions working but I am now a bit out of my depth and would LOVE for your input/assistance as the creator!

**Comment by godemperoroftheworld** [comment]
Mod is now rewritten for 1.18.x!

**Comment by XxInvictus** [comment]
I just want to confirm by the close that there is no intent to backport for 1.16.5? I only ask as a LOT of old/legacy 1.12 mod authors came out of the woodwork and updated their mods for 1.16 and have since dropped off the planet again not updating for 1.17 or 1.18

**Comment by godemperoroftheworld** [comment]
Yea, I don't think I'll be backporting for 1.16.x.
